# Generated by Django 5.1 on 2025-04-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediAccess', '0010_alter_patientrecord_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='professional_license_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
