# Generated by Django 5.1 on 2025-04-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediAccess', '0011_customuser_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='medicine_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
