# Generated by Django 5.1 on 2025-04-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediAccess', '0012_patientrecord_medicine_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='is_discharged',
            field=models.BooleanField(default=False),
        ),
    ]
