# Generated by Django 5.1 on 2026-05-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MediAccess", "0013_patientrecord_is_discharged"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="professional_license_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
